apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet-test-10apr
  janus-idp.io/tekton: dotnet-test-10apr
  backstage.io/kubernetes-id: dotnet-test-10apr
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-test-10apr
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
