apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-test-10apr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-test-10apr 
  name: dotnet-test-10apr
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet-test-10apr 
